# conda env create --file environment.yml
name: data_projects
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - seaborn
  - pandas
  - numpy
  - matplotlib
  - pip
  - pyprojroot
  - conda-forge::kagglehub
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - statsmodels
  - scipy
  - scikit-learn
  - python=3.12
  - upsetplot
  - missingno==0.5.2
  - unzip
  - plotly
  - pip:
    - pyhere